### ISSUE TITLE
Feature Request: use default workflow working directory

### ISSUE THREAD

**Issue by orestesgaolin** [invertase/github-action-dart-analyzer#8]
Hi there! We're looking into using this workflow in our process, but we found that it's necessary to provide the working directory explicitly. I think it would be much more convenient if the working directory was inferred from the GH Action defaults. e.g.:

```yaml
name: firebase_authentication_client

on:
  push:
    paths:
      - "packages/authentication_client/firebase_authentication_client/**"
      - ".github/workflows/firebase_authentication_client.yaml"

  pull_request:
    paths:
      - "packages/authentication_client/firebase_authentication_client/**"
      - ".github/workflows/firebase_authentication_client.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/authentication_client/firebase_authentication_client

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

...

      - name: Analyze
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
          annotate: true
          annotate-only: false
```

In the last step named `Analyze` the working directory should be the same as `defaults.working-directory`
